/* krpanoJS 1.0.8.14 videoplayer plugin (build 2011-12-20) */
var krpanoplugin=function(){function i(c){if(!(c==undefined||c==null||c==""||String(c).toLowerCase()=="null")){var f=unescape(d.parsePath(c));if(a&&b){a.havevideosize=false;a.isvideoready=false;a.iscomplete=false;a.ispaused=true;a.videourl=c;a.parsedurl=f;if(a.posterurl){var g=unescape(d.parsePath(a.posterurl)),e=document.createElement("img");e.addEventListener("error",function(){d.trace(3,"loading of "+g+" failed!")},false);e.addEventListener("load",function(){h(e.naturalWidth,e.naturalHeight);e=
null},false);e.src=g;b.poster=g}else if(d.isphone||d.ispad)h(320,240);b.src=f;if(a.pausedonstart)b.pause();else{b.autoplay="autoplay";b.play()}if(a.loop)if(d._isrealdesktop==false&&d.iosversion<"5")a._simulateloop=true;else b.loop="loop";if(a.html5controls)b.controls="controls";b.load()}}}function j(){if(a&&b){if(a.iscomplete)try{b.currentTime=0}catch(c){}b.play();a.ispaused=false}}function k(){if(a&&b){b.pause();a.ispaused=true}}function l(){if(a&&b){try{b.currentTime=0;b.pause()}catch(c){}a.ispaused=
true}}function m(){if(a&&b){a.havevideosize=false;a.isvideoready=false;a.iscomplete=false;a.ispaused=true;try{a.videourl=null;a.parsedurl=null;b.src=null}catch(c){}}}function n(){if(a&&b)if(b.playing==true||b.playing===undefined&&a.ispaused==false){b.pause();a.ispaused=true}else{b.play();a.ispaused=false}}function o(c){if(a&&b)try{b.currentTime=c}catch(f){}}function p(){b&&b.videoWidth>0&&b.videoHeight>0&&h()}function q(){b&&b.videoWidth>0&&b.videoHeight>0&&h()}function h(c,f){if(a&&b)if(a.havevideosize==
false){a.totaltime=b.duration;c&&f?a.registercontentsize(c,f):a.registercontentsize(b.videoWidth,b.videoHeight);a.havevideosize=true;a.isvideoready=true;d.call(a.onvideoready,a)}}function r(){if(a&&b){a.ispaused=false;d.view.haschanged=true}}function s(){if(a&&b){a.ispaused=true;d.call(a.onvideopaused,a)}}function t(){if(a&&b){a.time=b.currentTime;a.totaltime=b.duration}}function u(){if(d&&a)if(b&&a.loop&&a._simulateloop)b.play();else{a.iscomplete=true;d.call(a.onvideocomplete,a)}}function v(){if(d&&
a&&b){var c=null;c=b.error?b.error.code:0;(c=c==1?"video loading aborted":c==2?"network loading error":c==3?"video decoding failed":c==4?"loading video failed":"unknown error")&&d.trace(3,a.parsedurl+" - "+c+"!")}}var d=null,a=null,b=null;this.registerplugin=function(c,f,g){d=c;a=g;if(d.version<"1.0.8.14"||d.build<"2011-07-25")d.trace(3,"videoplayer plugin - too old krpano version (min. 1.0.8.14)");else{a.registerattribute("videourl",null);a.registerattribute("altvideourl",null);a.registerattribute("posterurl",
null);a.registerattribute("pausedonstart",false);a.registerattribute("loop",false);a.registerattribute("html5controls",false);a.registerattribute("volume",1);a.registerattribute("ispaused",false);a.registerattribute("iscomplete",false);a.registerattribute("isvideoready",false);a.registerattribute("havevideosize",false);a.registerattribute("time",0);a.registerattribute("totaltime",0);a.registerattribute("loadedbytes",0);a.registerattribute("totalbytes",0);a.registerattribute("onvideoready",null);a.registerattribute("onvideocomplete",
null);a.registerattribute("onvideopaused",null);a.registerattribute("onunsupported",null);a.registerattribute("playvideo",i);a.registerattribute("closevideo",m);a.registerattribute("stop",l);a.registerattribute("pause",k);a.registerattribute("play",j);a.registerattribute("resume",j);a.registerattribute("togglepause",n);a.registerattribute("seek",o);b=document.createElement("video");if(!b||!b.play||!b.pause){b=null;c=a.onunsupported;c==null||c==""||String(c).toLowerCase()=="null"?d.trace(2,"videoplayer plugin - HTML5 video is not supported by this browser!"):
d.call(c,a)}else{b.style.backgroundColor="#000000";b.style.width="100%";b.style.height="100%";b.onselectstart=function(){return false};b.addEventListener("loadedmetadata",p,false);b.addEventListener("loadeddata",q,false);b.addEventListener("timeupdate",t,false);b.addEventListener("play",r,false);b.addEventListener("pause",s,false);b.addEventListener("ended",u,false);b.addEventListener("error",v,false);b.addEventListener("touchstart",function(e){e.preventDefault()},true);i(a.altvideourl?a.altvideourl:
a.videourl);a.sprite.appendChild(b)}}};this.unloadplugin=function(){try{a&&a.sprite&&b&&a.sprite.removeChild(b)}catch(c){}d=a=b=null}};
