<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

//require_once('services360.inc');

/**
 * Implementation of hook_ctools_plugin_api().
 */
function services360_ctools_plugin_api($owner, $api) {
//  if ($owner == 'services' && $api == 'services') {
//    return array(
//      'version' => 3,
//      'file' => 'services360.inc', // Optional parameter to indicate the file name to load.
//      'path' => drupal_get_path('module', 'services360'), // If specifying the file key, path is required.
//    );
//  }
}

function services360_init() {
  //krumo('asd');
}


function services360_services_resources() {
  print 'asdadf';
}
/**
* Implements hook_default_services_endpoint().
*/
function services360_default_services_endpoint() {
  $endpoints = array();

  $endpoint = new stdClass;
  $endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
  $endpoint->api_version = 3;
  $endpoint->name = 'service360api';
  $endpoint->title = 'Service 360 API';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'service360';
  //$endpoint->authentication = array();
  $endpoint->server_settings = '';
  $endpoint->resources = array(
    'system' => array(
      'actions' => array(
        'connect' => array(
          'enabled' => 1,
        ),
      ),
    ),
    'user' => array(
      'alias' => 'users',
      'operations' => array(
        'retrieve' => array(
          'enabled' => 1,
        ),
        'create' => array(
          'enabled' => 1,
        ),
        'update' => array(
          'enabled' => 1,
        ),
        'delete' => array(
          'enabled' => 1,
        ),
        'index' => array(
          'enabled' => 1,
        ),
      ),
      'actions' => array(
        'login' => array(
          'enabled' => 1,
        ),
        'logout' => array(
          'enabled' => 1,
        ),
        'register' => array(
          'enabled' => 1,
        ),
      ),
    ),
  );
  $endpoint->debug = 0;
  
  $endpoints[] = $endpoint;

  return $endpoints;
}

