<?php
$loc = $_GET['loc'];
$english = (!isset($loc) || $loc != 'es');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo ($english ? 'Terms of Service' : 'Términos de Servicio'); ?></title>
<style type="text/css">
body {
	margin-left: 20px;
	margin-top: 20px;
	margin-right: 20px;
	margin-bottom: 20px;
}
</style>
</head>
<body style="background-color:#000">
<div style="text-align:justify;color:#FFF;font-family:Verdana, Geneva, sans-serif;font-size:medium;width:100%">
      <center><img src="ecuador360_image.png" width="260" height="56" /></center>
<?php if($english) { ?>
	  <center><h2><strong>Terms of Service</strong></h2></center>
      <p>These Terms of Service (&quot;<strong>Terms</strong>&quot;) govern your access to and use of the services and  ecuador360.travel's websites (the &quot;<strong>Services</strong>&quot;), and any information, text, graphics, photos or other materials uploaded,  downloaded or appearing on the Services (collectively referred to as &quot;<strong>Content</strong>&quot;). Your access to and use of the Services is conditioned on your  acceptance of and compliance with these Terms. By accessing or using the  Services you agree to be bound by these Terms.</p>
      <h3 align="left">Basic Terms</h3>
      <p>You are responsible for your use of the  Services, for any Content you post to the Services, and for any consequences  thereof. The Content you submit, post, or display will be able to be viewed by  other users of the Services and through third party services and websites  through a hiperlink with www.ecuador360.travel.You should only provide Content  that you are comfortable sharing with others under these Terms.</p>
      <p>You may use the Services only if you accept  this terms with ecuador360.travel and accept to receive the services under the  laws of the República of Ecuador or other applicable jurisdiction. You may use  the Services only in compliance with these Terms and all applicable local,  state, national, and international laws, rules and regulations.<br />
        The Services that ecuador360.travel provides  are always evolving and the form and nature of the Services that  ecuador360.travel provides may change from time to time without prior notice to  you. In addition, ecuador360.travel may stop (permanently or temporarily)  providing the Services (or any features within the Services) to you or to users  generally and may not be able to provide you with prior notice. We also retain  the right to create limits on use and storage at our sole discretion at any  time without prior notice to you.<br />
        The Services may include advertisements, which  may be targeted to the Content or information on the Services, queries made  through the Services, or other relavant information based on CAPTUR´s criteria.  The types and extent of advertising by ecuador360.travel on the Services are  subject to change. <br />
        In consideration for ecuador360.travel granting  you access to and use of the Services, you agree that ecuador360.travel and its  third party providers and partners may place such advertising on the Services  or in connection with the display of Content or information from the Services  whether submitted by you or others.</p>
      <h3 align="left">Privacy</h3>
      <p>Any information that you provide to ecuador360.travel  is subject to our&nbsp;Privacy  Policy which governs our collection and use of your information. You understand  that through your use of the Services you consent to the collection and use (as  set forth in the Privacy Policy) of this information, including the transfer of  this information to other countries for storage, processing and use by ecuador360.travel.  As part of providing you the Services, we may need to provide you with certain  communications, such as service announcements and administrative messages.  These communications are considered part of the Services and your ecuador360.travel´s  account, which you may not be able to opt-out from receiving.</p>
      <h3 align="left">Passwords</h3>
      <p>You are responsible for safeguarding the  password that you use to access the Services and for any activities or actions  under your password. We encourage you to use &quot;strong&quot; passwords  (passwords that use a combination of upper and lower case letters, numbers and  symbols) with your account. Ecuador360.travel cannot and will not be liable for  any loss or damage arising from your failure to comply with the above  requirements.</p>
      <h3 align="left">Content on the Services</h3>
      <p>All Content, whether publicly posted or  privately transmitted, is the sole responsibility of the person who originated  such Content. We may not monitor or control the Content posted via the Services  and, we cannot take responsibility for such Content. Any use or reliance on any  Content or materials posted via the Services or obtained by you through the  Services is at your own risk.<br />
        We do not endorse, support, represent or  guarantee the completeness, truthfulness, accuracy, or reliability of any  Content or communications posted via the Services or endorse any opinions  expressed via the Services. You understand that by using the Services, you may  be exposed to Content that might be offensive, harmful, inaccurate or otherwise  inappropriate. Under no circumstances will ecuador360.travel be liable in any  way for any Content, including, but not limited to, any errors or omissions in  any Content, or any loss or damage of any kind incurred as a result of the use  of any Content posted, emailed, transmitted or otherwise made available via the  Services or broadcast elsewhere.</p>
      <h3 align="left">User´s Rights</h3>
      <p>You retain your rights to any Content you  submit, post or display on or through the Services. By submitting, posting or  displaying Content on or through the Services, you grant us a worldwide,  non-exclusive, royalty-free license (with the right to sublicense) to use,  copy, reproduce, process, adapt, modify, publish, transmit, display and  distribute such Content in any and all media or distribution methods.</p>
      <p>You agree that this license includes the right  for ecuador360.travel to make such Content available to other companies,  organizations or individuals who partner with Twitter for the syndication,  broadcast, distribution or publication of such Content on other media and  services, subject to our terms and conditions for such Content use.</p>
      <p>Ecuador360.travel, or other companies,  organizations or individuals who partner with us, may be made with no  compensation paid to you with respect to the Content that you submit, post,  transmit or otherwise make available through the Services.<br />
        We may modify or adapt your Content in order  to transmit, display or distribute it over computer networks and in various  media and/or make changes to your Content as are necessary to conform and adapt  that Content to any requirements or limitations of any networks, devices,  services or media.<br />
        You are responsible for your use of the  Services, for any Content you provide, and for any consequences thereof,  including the use of your Content by other users and our third party partners.  You understand that your Content may be rebroadcasted by our partners and if  you do not have the right to submit Content for such use, it may subject you to  liability. Ecuador360.travel will not be responsible or liable for any use of  your Content by ecuador360.travel in accordance with these Terms. You represent  and warrant that you have all the rights, power and authority necessary to  grant the rights granted herein to any Content that you submit and will  compensate to any person disadvantaged and the provider or to  ecuador360.travel´s legal representative by any effect result of the lack of  the capacity to perform the terms  said  before.</p>
      <h3 align="left">Ecuador360.travel´s Rights </h3>
      <p>All right, title, and interest in and to the  Services (excluding Content provided by users) are and will remain the  exclusive property of ecuador360.travel  and its licensors. The Services are protected  by copyright, trademark, and other laws of the República del Ecuador. Nothing  in the Terms gives you a right to use the ecuador360.travel name or any of its trademarks,  logos, domain names, and other distinctive brand features. Any feedback,  comments, or suggestions you may provide regarding ecuador360.travel, or the  Services is entirely voluntary and we will be free to use such feedback,  comments or suggestions as we see fit and without any obligation to you.</p>
      <h3 align="left">Restrictions on Content  and Use of the Services</h3>
      <p>We reserve the right at all times (but will  not have an obligation) to remove or refuse to distribute any Content on the  Services and to terminate users or reclaim usernames. We also reserve the right  to access, read, preserve, and disclose any information as we reasonably  believe is necessary to (i) satisfy any applicable law, regulation, legal  process or governmental request, (ii) enforce the Terms, including  investigation of potential violations hereof, (iii) detect, prevent, or  otherwise address fraud, security or technical issues, (iv) respond to user  support requests, or (v) protect the rights, property or safety of ecuador360.travel,  its users and the public.</p>
      <p>The user may not do any of the following while  accessing or using the Services: (i) access, tamper with, or use non-public  areas of the Services, ecuador360.travel’s computer systems, or the technical  delivery systems of ecuador360.travels providers; (ii) probe, scan, or test the  vulnerability of any system or network or breach or circumvent any security or  authentication measures; (iii) access or search or attempt to access or search  the Services by any means (automated or otherwise) other than through our  currently available, published interfaces that are provided by ecuador360.travel  (and only pursuant to those terms and conditions), unless you have been  specifically allowed to do so in a separate written agreement with ecuador360.travel,  or (v) interfere with, or disrupt, (or attempt to do so), the access of any  user, host or network, including, without limitation, sending a virus,  overloading, flooding, spamming, mail-bombing the Services, or by scripting the  creation of Content in such a manner as to interfere with or create an undue  burden on the Services.</p>
      <h3 align="left">Copyright Policy</h3>
      <p>Ecuador360.travel respects the intellectual  property rights of others and expects users of the Services to do the same. We  will respond to notices of alleged copyright infringement that comply with  applicable law and are properly provided to us. If you believe that your  Content has been copied in a way that constitutes copyright infringement,  please provide us with the following information: (i) a physical or electronic  signature of the copyright owner or a person authorized to act on their behalf;  (ii) identification of the copyrighted work claimed to have been infringed;  (iii) identification of the material that is claimed to be infringing or to be  the subject of infringing activity and that is to be removed or access to which  is to be disabled, and information reasonably sufficient to permit us to locate  the material; (iv) your contact information, including your address, telephone  number, and an email address; (v) a statement by you that you have a good faith  belief that use of the material in the manner complained of is not authorized  by the copyright owner, its agent, or the law; and (vi) a statement that the  information in the notification is accurate, and, under penalty of perjury,  that you are authorized to act on behalf of the copyright owner.<br />
        We reserve the right to remove Content alleged  to be infringing without prior notice and at our sole discretion. In  appropriate circumstances, ecuador360.travel will also terminate a user’s  account if the user is determined to be a infringer. Our designated address for  notice of alleged copyright infringement appearing on the Services is:<br />
        Cámara Provincial de Turismo de Pichincha. Att:  Ecuador360.travel. Dirección: Rumipamba n33-319 y Av Amazonas. Edif. torre  Carolina, Piso 10. P.O Box. 1716 1864. Quito Ecuador.<br />
        Email: <a href="mailto:ecuador360@captur.com">ecuador360@captur.com</a></p>
      <h3 align="left">The Services are Available  &quot;AS-IS&quot;</h3>
      <p>Your access to and use of the Services or any  Content is at your own risk. You understand and agree that the Services is  provided to you on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis.  Without limiting the foregoing, Ecuador360.travel AND ITS PARTNERS DISCLAIM ANY  WARRANTIES, EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR  PURPOSE, OR NON-INFRINGEMENT. We make no warranty and disclaim all  responsibility and liability for the completeness, accuracy, availability, timeliness,  security or reliability of the Services or any content thereon. Twitter will  not be responsible or liable for any harm to your computer system, loss of  data, or other harm that results from your access to or use of the Services, or  any Content. You also agree that ecuador360.travel has no responsibility or  liability for the deletion of, or the failure to store or to transmit, any  Content and other communications maintained by the Services. We make no  warranty that the Services will meet your requirements or be available on an  uninterrupted, secure, or error-free basis. No advice or information, whether  oral or written, obtained from ecuador360.travel or through the Services, will  create any warranty not expressly made herein.</p>
      <h3 align="left">Links</h3>
      <p>The Services may contain links to third-party  websites or resources. You acknowledge and agree that we are not responsible or  liable for: (i) the availability or accuracy of such websites or resources; or  (ii) the content, products, or services on or available from such websites or  resources. Links to such websites or resources do not imply any endorsement by ecuador360.travel  of such websites or resources or the content, products, or services available  from such websites or resources. You acknowledge sole responsibility for and  assume all risk arising from your use of any such websites or resources.</p>
      <h3 align="left">Limitation of Liability</h3>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE  LAW, ECUADOR360.TRAVEL AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES,  AGENTS, PARTNERS AND LICENSORS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT,  INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT  LIMITATION, LOSS OF PROFITS, DATA, USE, GOOD-WILL, OR OTHER INTANGIBLE LOSSES,  RESULTING FROM (i) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE  SERVICES; (ii) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES,  INCLUDING WITHOUT LIMITATION, ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF  OTHER USERS OR THIRD PARTIES; (iii) ANY CONTENT OBTAINED FROM THE SERVICES; AND  (iv) UNAUTHORIZED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT,  WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE) OR ANY OTHER  LEGAL THEORY, WHETHER OR NOT ECUADOR360.TRAVEL HAS BEEN INFORMED OF THE  POSSIBILITY OF SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO  HAVE FAILED OF ITS ESSENTIAL PURPOSE.</p>
      <h3 align="left">Exclusions</h3>
      <p>Some jurisdictions do not allow the exclusion  of certain warranties or the exclusion or limitation of liability for  consequential or incidental damages, so the limitations above may not apply to  you.</p>
      <h3 align="left">Waiver and Severability</h3>
      <p>The failure of ecuador360.travel to enforce  any right or provision of these Terms will not be deemed a waiver of such right  or provision. In the event that any provision of these Terms is held to be  invalid or unenforceable, the remaining provisions of these Terms will remain  in full force and effect.</p>
      <h3 align="left">Controlling Law and  Jurisdiction</h3>
      <p>These Terms and any action related thereto  will be governed by the laws of the Republic of Ecuador without regard to or  application of its conflict of law provisions or the user´s state or country of  residence. All claims, legal proceedings or litigation arising in connection  with the Services will be brought solely in Quito city, pichincha province-Ecuador,  and you consent to the jurisdiction of and venue in such courts and waive any  objection as to inconveniente charter, jurisdiction, capability or any alike.  If you are accepting these Terms on behalf of a United States federal  government entity that is legally unable to accept the controlling law,  jurisdiction or venue clauses above, then those clauses do not apply to you but  instead these Terms and any action related thereto will be will be governed by  the laws of the Republic of Ecuador (without reference to conflict of laws)  and, in the absence of any law, the applicable will be the same legislation of  the republic  of Ecuador or what it´s  judges, authorities and magistrales resolve.</p>
      <h3 align="left">Entire Agreement</h3>
      <p>These Terms, the ecuador360.travel Rules and  our Privacy Policy are the entire and exclusive agreement between ecuador360.travel  and you regarding the Services (excluding any services for which you have a  separate agreement with ecuador360.travel that is explicitly in addition or in  place of these Terms), and these Terms supersede and replace any prior  agreements between ecuador360.travel and you regarding the Services. </p>
      <p>We may revise these Terms from time to time,  the most current version will always be at www.ecuador360.travel. If the  revision, in our sole discretion, is material we will notify you via an  annoucement in ecuador360.travel. By continuing to access or use the Services  after those revisions become effective, you agree to be bound by the revised  Terms.<br />
        These Services are operated and provided by Cámara  Provincial de Turismo de Pichincha. Att: Ecuador360.travel. Dirección:  Rumipamba n33-319 y Av Amazonas. Edif. torre Carolina, Piso 10. P.O Box. 1716  1864.  Quito Ecuador.<br />
        Email: <a href="mailto:ecuador360@captur.com">ecuador360@captur.com</a> <br />
        If you  have any questions about these Terms, please&nbsp;contact us</p>
  <p><em>Effective: December 15th 2011</em></p>
<?php } else { ?>  
  <center><strong><h2>Términos de Servicio</h2></strong></center>Estos términos del servicio (<strong>términos</strong>) regulan el acceso y la utilización de los servicios y sitios web y  aplicaciones de www.ecuador360.travel (los &quot;<strong>Servicios</strong>&quot;),  y cualquier otra información, texto, gráficos, fotos, imágenes u otros materiales  cargado, descargado o que aparezca en los Servicios (denominados colectivamente  como &quot;<strong>Contenido</strong>&quot;). El acceso y uso de los servicios está  condicionado a la aceptación y el cumplimiento de las presentes Condiciones. Al  acceder o utilizar los Servicios usted acepta que quedará vinculado por estas  Condiciones.</p>
  <h3>Condiciones básicas</h3>
  <p>El usuario es responsable del uso de los  Servicios, por cualquier Contenido que publique en los Servicios y de las  consecuencias derivadas. El Contenido que envíe, publique, o muestre, podrá ser  visto por otros usuarios de los Servicios a través de servicios y sitios web de  terceros a través de un hipervínculo con la página web www.ecuador360.travel.  Sólo deberá proporcionar el Contenido que quiera compartir con otras personas  en estos Términos.</p>
  <p>El usuario únicamente podrá hacer uso de estos  Servicios si acepta esta relación convencional vinculante con  <a href="http://www.ecuador360.travel">www.ecuador360.travel</a> como también a recibir dichos servicios según  las leyes Ecuador u otra jurisdicción aplicable. El usuario sólo podrá hacer  uso de dichos Servicios conforme a dichas Condiciones como a toda ley,  normativa o reglamento aplicable sea local, estatal, nacional o internacional.<br />
    Los Servicios que ecuador360.travel proporciona  están siempre evolucionando y la forma y la naturaleza de dichos Servicios  podrá cambiar eventualmente sin previo aviso. Además, ecuador360.travel podrá  cesar (permanente o temporalmente) de proveer estos Servicios (o cualquier  artículo o parte de estos Servicios) al usuario y/o usuarios con o sin previo  aviso. Ecuador360.travel se reserva el derecho de limitar el uso o almacenaje  bajo su única discreción en cualquier momento sin previo aviso.<br />
    Los Servicios pueden incluir anuncios, los  cuales pueden estar referidos al Contenido o información de los Servicios,  preguntas hechas a través de dichos Servicios u otra información relevante a  criterio de CAPTUR. El tipo y extensión de la publicidad de ecuador360.travel  en los Servicios están sujetos a cambio. Considerando que ecuador360.travel  garantiza el acceso y uso a los Servicios por parte del usuario; el usuario  acepta que ecuador360.travel y terceras partes proveedoras o socias a  ecuador360.travel emplacen publicidad en los Servicios o en relación con el  Contenido, o información de los Servicios ya esté publicado por el usuario u  otros.</p>
  <h3>Privacidad</h3>
  <p>Cualquier información que el usuario  suministre a ecuador360.travel está sujeta a nuestra Política de Privacidad,  que rige nuestra recolección y uso de la información. El usuario entiende que a  través del uso de los Servicios da su consentimiento a la recolección y uso  (tal como se establece en la Política de Privacidad) de esta información,  incluyendo la transferencia de esta información a otros países para  almacenamiento, procesamiento y uso por parte de ecuador360.travel. Como parte  de nuestra prestación de Servicios, quizás necesitemos entregar ciertas  comunicaciones, tales como anuncios de servicios y mensajes administrativos.  Estas comunicaciones son consideradas parte de los Servicios y de la cuenta  ecuador360.travel, y el usuario podría no poder optar por no recibirlas.</p>
  <h3>Contraseñas</h3>
  <p>Usted es responsable de salvaguardar la  contraseña que utiliza para acceder a los Servicios y para cualquier actividad  o acciones bajo su contraseña. Le animamos a usar contraseñas  &quot;fuertes&quot; (contraseñas que utilizan una combinación de letras mayúsculas  y minúsculas, números y símbolos) con su cuenta. Ecuador360.travel no puede y  no será responsable por cualquier pérdida o daño causado por su incumplimiento  de los requisitos anteriores.</p>
  <h3>Contenido de los servicios</h3>
  <p>La responsabilidad de todo contenido, publica  o privadamente difundido, recae en el autor de dicho contenido.  Ecuador360.travel no supervisa ni controla el Contenido publicado vía dichos  &quot;Servicios&quot; y no se hace responsable de dicho Contenido. Cualquier  uso o dependencia de cualquiera de estos Contenidos o materiales publicados a  través de este Servicio, u obtenidos por el usuario a través de estos Servicios  es por cuenta y riesgo del usuario.<br />
    Ecuador360.travel no aprueba, apoya,  representa o garantiza la veracidad, exactitud o fiabilidad de ningún Contenido  o comunicado publicado a través de los Servicios ni respalda ninguna opinión  expresada a través de dichos Servicios. El usuario entiende que en estos  Servicios puede aparecer con Contenido ofensivo, dañino, inexacto o de algún  modo inapropiado. Ecuador360.travel no se responsabilizará, bajo ninguna  circunstancia y de ningún modo, de ningún Contenido, incluyendo pero sin  limitarse a, cualquier error u omisión en el Contenido, pérdida o daño de  cualquier tipo sucedidos como resultado de la utilización de cualquier  Contenido publicado, enviado por correo electrónico, transmitido o puesto a  disposición a través de los Servicios o emitidos en otros medios de difusión.</p>
  <h3>Derechos del usuario</h3>
  <p>El usuario se reserva los derechos de  cualquier contenido enviado, publicado o presentado a través de los Servicios.  Al enviar, publicar o presentar cualquier Contenido a través de estos  Servicios, el usuario otorga a ecuador360.travel licencia mundial, no  exclusiva, libre de regalías (con derecho a la concesión de la licencia a  terceros) para utilizar, copiar, reproducir, procesar, adaptar, modificar,  publicar, transmitir, mostrar y distribuir dicho Contenido cualquier medio de  comunicación o método de distribución (actual o desarrollado en un futuro).<br />
    El usuario acepta que este permiso otorga el  derecho a ecuador360.travel de poner a la disposición de otras compañías,  organizaciones o individuos asociados con ecuador360.travel el Contenido para  la sindicación, difusión, distribución o publicación de dicho Contenido en  otros medios y servicios, según  nuestras  Condiciones generales para utilizarlo.<br />
    Ecuador360.travel, otras compañías,  organizaciones o personas asociadas con Ecuador360.travel podrán llevar a cabo  tales usos adicionales sin compensar de ninguna manera al usuario que ha  enviado, publicado, transmitido o puesto a disposición Contenido a través de  los Servicios.<br />
    Ecuador360.travel puede modificar o adaptar el  Contenido del usuario a fin de transmitir, mostrar o distribuirlo a través de  la red así como en diversos medios de comunicación y/o realizar los cambios  necesarios para ajustar y adaptar dicho Contenido a cualquier requisito o  limitación de redes, aparatos, servicios o medios de comunicación.</p>
  <p>El usuario es responsable del uso de dichos  Servicios, de cualquier Contenido y consecuencias del mismo, incluyendo el uso  de su Contenido por parte de otros usuarios y por terceras partes asociadas. El  usuario entiende que su Contenido puede ser retransmitido por nuestros  asociados y si el usuario no poseyera el derecho de presentar dicho Contenido  para tal uso, la <u>responsabilidad</u> será del usuario. Ecuador360.travel no  se hará responsable ni se le considerará como tal, del uso del Contenido del  usuario por parte de ecuador360.travel según estas Condiciones. El usuario  manifiesta y garantiza que tiene todos los derechos, poderes y autoridad  necesarios para conceder los derechos otorgados en este documento de cualquier  Contenido que el usuario envíe. Y resarcirá a los perjudicados y al proveedor o  titular de Ecuador360.travel por cualquier efecto que se produzca como  consecuencia de la falta de poder y capacidad del usuario respecto a las  obligaciones mencionadas y su capacidad</p>
  <h3>Derechos de ecuador360.travel</h3>
  <p>Todo derecho, título o interés de y para los  Servicios (excluyendo el Contenido proporcionado por los usuarios) son y  seguirán siendo de exclusiva propiedad de ecuador360.travel y sus cedentes. Los  Servicios están protegidos por derechos de autor, marca registrada y otras  leyes de Ecuador. Estas Condiciones no otorgan en ningún momento derecho alguno  al usuario de utilizar el nombre, marca registrada, logotipo, dominio u otra  característica distintiva de la marca. Cualquier respuesta, comentario o  sugerencia que el usuario proporcione con respecto a ecuador360.travel o a  dichos Servicios es completamente voluntaria y ecuador360.travel es libre de  utilizar tal información, comentarios o sugerencias que considere oportuno sin  ninguna obligación hacia el usuario.</p>
  <h3>Restricciones en el  Contenido y Uso de los Servicios</h3>
  <p>Nos reservamos el derecho en todo momento  (pero no tendremos una obligación) de borrar o negarnos a distribuir algún  contenido en los servicios y de eliminar usuarios o reclamar nombres de  usuarios. También nos reservamos el derecho de acceder, leer, preservar, y  hacer pública cualquier información como razonablemente pensamos que es  necesaria para (i) satisfacer cualquier ley aplicable, regulación, proceso  legal o petición del gobierno, (ii) hacer cumplir los Términos, incluyendo la  investigación de violaciones potenciales del mismo, (iii) detectar, prevenir, o  de otra forma provocar fraude, problemas de seguridad o técnicos, (iv)  responder las peticiones de soporte del usuario, o (v) proteger los derechos,  propiedad o seguridad de ecuador360.travel, sus usuarios y al público.</p>
  <p>El usuario no está autorizado a realizar  ninguna de las siguientes acciones al acceder o utilizar estos Servicios: (I)  acceder, manipular indebidamente o utilizar áreas no públicas de los Servicios,  de los sistemas informáticos de ecuador360.travel, los sistemas técnicos de  ejecución de proveedores de ecuador360.travel, (II)examinar, escanear o probar  la vulnerabilidad de ningún sistema, o bien conectarse, traspasar o franquear cualquier  medida de seguridad; (III) acceder, investigar o intentar acceder o investigar  a los Servicios por algún método (automatizado o no) que no sea a través de los  interfaces que ecuador360.travel ha dispuesto y publicado (y únicamente  conforme a los Condiciones generales mencionadas), a menos que usted haya sido  específicamente autorizado a hacerlo en un acuerdo adicional <u>escrito previo</u> con ecuador360.travel.  (IV) falsificar  cualquier cabecera TCP/IP o cualquier parte de la información de la cabecera en  cualquier correo electrónico o publicación, o la utilización del Servicio de  cualquier manera para enviar información identificativa de la fuente alterada,  engañosa o falsa; o (V) interferir, o deteriorar (o intentar hacerlo) el acceso  de cualquier usuario, servidor o red , incluyendo pero sin limitarse a, enviar  virus, sobrecargar, desbordar, mandar correo basura, o bombardear con correo  electrónico los Servicios, o usando un script para la creación del Contenido de  tal manera que interfiera o genere una carga indebida en los Servicios.</p>
  <h3>Política de Derechos de  Autor</h3>
  <p>Ecuador360.travel respeta la propiedad  intelectual de otros y espera que los usuarios de los Servicios hagan lo mismo.  Ecuador360.travel responderá a notificaciones de supuesta vulneración de los  derechos de autor que cumpla con la ley vigentes y sean proporcionada a  ecuador360.travel de manera apropiada. Si el usuario creyera que su Contenido  ha sido copiado de manera que constituya violación de los derechos de autor,  ecuador360.travel pide encarecidamente que se proporcione la siguiente  información: (I) firma física o electrónica de los derechos de autor del  propietario o de la persona autorizada para actuar en su representación. (II)  identificación de la propiedad que posee los derechos autor que alega haber  sido violada. (III) identificación de la propiedad que alega haber sido violada  o de ser objeto de la violación de sus derechos de autor y que debe ser  eliminada o prohibir el acceso a lo que debe ser inhabilitado, y toda  información pertinente para permitir a Twitter la localización del material.  (IV) la información del usuario, incluyendo la dirección, el número de teléfono  y la dirección electrónica; (V) la declaración del usuario que cree de buena fe  que el material según la manera que ha sido expuesto, no está autorizado por el  titular de los derechos de autor, su representante o la ley; y (VI) una  declaración confirmando que la información de la notificación es precisa y,  bajo pena de perjurio, que el usuario está autorizado a actuar en  representación del titular de los derechos de autor.<br />
    Ecuador360.travel se reserva el derecho de  quitar contenido supuestamente infractor sin noticia previa y bajo su única  discreción. Bajo determinadas circunstancias, ecuador360.travel podrá también  cerrar la cuenta de un usuario si éste resultara contraventor. La dirección, en  caso de necesitar la notificación de supuesto quebrantamiento del derecho de  autor que aparece en los Servicios es:<br />
    Cámara Provincial de Turismo de Pichincha.  Att: Ecuador360.travel. Dirección: Rumipamba n33-319 y Av Amazonas. Edif. torre  Carolina, Piso 10. P.O Box. 1716 1864. Quito Ecuador.<br />
    Email: <a href="mailto:ecuador360@captur.com">ecuador360@captur.com</a></p>
  <h3>Los Servicios están  Disponibles &quot;TAL-CUAL&quot;</h3>
  <p>El acceso y uso de los Servicios o cualquier  contenido es bajo su propio riesgo. Usted entiende y acepta que el Servicio se  le proporciona &quot;TAL CUAL&quot; y &quot;SEGÚN DISPONIBILIDAD&quot;. Sin  perjuicio de lo anterior, Ecuador360.travel Y SUS SOCIOS RECHAZAN CUALQUIER  GARANTÍA, EXPRESA O IMPLÍCITA, DE COMERCIALIZACIÓN, IDONEIDAD PARA UN PROPÓSITO  PARTICULAR O NO INFRACCIÓN. No ofrecemos ninguna garantía y declinamos toda  responsabilidad por la integridad, exactitud, disponibilidad, oportunidad,  seguridad o fiabilidad del Servicio o de cualquier contenido. Ecuador360.travel  no se hace responsable de cualquier daño a su sistema informático, la pérdida  de datos, u otro daño que resulte de su acceso o uso de los Servicios, o de  cualquier Contenido. También acepta que ecuador360.travel no tiene ninguna  responsabilidad u obligación por la supresión o no almacenamiento o transmisión  del contenido y otras comunicaciones mantenidas por los Servicios. No ofrecemos  ninguna garantía de que los servicios satisfagan sus necesidades o que estén  disponibles de manera ininterrumpida, segura o libre de errores. Ningún consejo  o información, ya sea oral o escrito, obtenido a partir de ecuador360.travel o a  través de los Servicios, creará ninguna garantía no expresamente en el  presente.</p>
  <h3>Links</h3>
  <p>Los Servicios pueden contener enlaces a sitios  web o recursos de terceras partes. El usuario conoce y acepta que ecuador360.travel  no es responsable de (I) la disponibilidad o precisión de tales sitios web o  recursos externos, o (II) el contenido, productos o servicios de estos o  disponibles en tales sitios web o recursos externos. Los enlaces a estos sitios  web o recursos externos no implican apoyo por parte de ecuador360.travel a  tales sitios o recursos, o al contenido, productos o servicios disponibles en  tales sitios o recursos. El usuario conoce y asume toda responsabilidad y  riesgo derivado del uso de cualquiera de estos sitios web o recursos externos.</p>
  <h3>Limitación de  Responsabilidad</h3>
  <p>EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY  APLICABLE, ECUADOR360.TRAVEL y SUS SUBSIDIARIAS, AFILIADOS, OFICIALES,  EMPLEADOS, AGENTES, SOCIOS Y LICENCIAS NO SERÁN RESPONSABLES POR DAÑOS  DIRECTOS, INDIRECTOS, INCIDENTALES, ESPECIALES, CONSECUENTES O PUNITIVOS,  INCLUYENDO SIN LIMITACIÓN, PÉRDIDA DE BENEFICIOS, DATOS, USO, BUENA VOLUNTAD, U  OTRAS PÉRDIDAS INTANGIBLES, COMO RESULTADO DE (I) TU ACCESO O USO O  IMPOSIBILIDAD DE ACCEDER O UTILIZAR EL SERVICIO, (ii) CUALQUIER CONTENIDO O  CONDUCTA DE CUALQUIER TERCERO SOBRE LOS SERVICIOS, INCLUYENDO SIN LIMITACIÓN,  CUALQUIER ACTO DE DIFAMACIÓN, OFENSA O ILEGAL DE OTROS USUARIOS O TERCEROS,  (iii) CUALQUIER CONTENIDO OBTENIDO DE LOS SERVICIOS Y (iv) EL ACCESO NO  AUTORIZADO, USO O LA ALTERACIÓN DE SUS TRANSMISIONES O CONTENIDO, YA SEA BASADO  EN GARANTÍAS, AGRAVIO (INCLUYENDO NEGLIGENCIA) O CUALQUIER OTRA TEORÍA LEGAL,  YA SEA QUE ECUADOR360.TRAVEL ESTÉ INFORMADO DE LA POSIBILIDAD DE TALES DAÑOS, Y  AUNQUE UN RECURSO ESTIPULADO EN ESTE DOCUMENTO ES QUE HAN FRACASADO EN SU  PROPÓSITO ESENCIAL.</p>
  <h3>Exclusiones</h3>
  <p>Algunas jurisdicciones no permiten la  exclusión de ciertas garantías o la exclusión o limitación de responsabilidad  por daños y perjuicios consiguientes y/o fortuitos, por lo que las limitaciones  expuestas anteriormente pueden no ser aplicables.</p>
  <h3>Cláusula de cesión y  nulidad parcial</h3>
  <p>El fracaso por parte de ecuador360.travel de  hacer cumplir cualquier derecho o disposición de estas Condiciones no se  considerará como cesión de tal derecho o disposición. En caso de que alguna  disposición de estas Condiciones resultara inválida o no aplicable, las  restantes disposiciones de estas Condiciones seguirán en pleno vigor y efecto.</p>
  <h3>Ley aplicable y  jurisdicción competente</h3>
  <p>Estas Condiciones o cualquier otra acción  relativa a ellas estarán regidas por las leyes de la República del Ecuador sin  tener en cuenta o aplicación las cláusulas de Conflicto de leyes del estado o  país de residencia del usuario. Toda reclamación, procedimiento legal o litigio  surgida en relación con estos Servicios, procedimientos legales o litigios  originados en relación con los Servicios tendrá lugar únicamente en la ciudad  de Quito, provincia de Pichincha-Ecuador, y el usuario acepta dicha  jurisdicción y lugar en tales tribunales y renuncia a cualquier objeción en cuanto  a la inconveniencia de fuero, jurisdicción, competencia o similares. Si el  usuario acepta estas Condiciones en representación de una entidad del gobierno  federal de los Estados Unidos legalmente incapaz de aceptar la ley aplicable,  jurisdicción o lugar de las cláusulas citadas más arriba, dichas cláusulas no  serán aplicadas al usuario, sino en lugar de dichas Condiciones o cualquier  acción en relación a ellas será las leyes la República del Ecuador las que se  consideren aplicables / regido (referente a al Conflicto de leyes) y, en  ausencia de ley  igualmente la misma  legislación de la República o lo que sus jueces, autoridades o magistrados  resuelvan .</p>
  <h3>Totalidad del acuerdo y  convenio entre las partes </h3>
  <p>Estos términos, el Reglamento de  ecuador360.travel y nuestra Política de Privacidad, constituyen el acuerdo completo  y exclusivo entre ecuador360.travel y usted en relación con los Servicios  (excluyendo aquellos servicios para los que tiene un acuerdo separado con  ecuador360.travel que es explícitamente, además o en lugar de estos términos),  y las presentes Condiciones sustituyen y reemplazan cualquier acuerdo anterior  entre usted con respecto a ecuador360.travel y los Servicios. <br />
    Revisaremos estas Condiciones de vez en  cuando, la versión más actual siempre publicada en www.ecuador360.travel. Si la  revisión, a nuestro criterio, es sustancial se lo notificaremos a través de un  anuncio en la web ecuador360.travel. Al continuar accediendo o utilizando los  Servicios después de las revisiones, el usuario acepta quedar obligado por las  Condiciones revisadas.<br />
    Estos servicios son operados y proporcionados  por: Cámara Provincial de Turismo de Pichincha. Att: Ecuador360.travel.  Dirección: Rumipamba n33-319 y Av Amazonas. Edif. torre Carolina, Piso 10. P.O  Box. 1716 1864. Quito Ecuador.<br />
    Email: <a href="mailto:ecuador360@captur.com">ecuador360@captur.com</a> <br />
    Si  tiene alguna duda sobre estos Términos, por favor póngase en contacto.<br />
  <em>Entra en  vigor el: 15 de diciembre de 2011.</em></p>
<?php } ?>
</div>
</body>
</html>