<?php
/*
 * hook_init
 */
function krpano_init() {

}

/*
 * Function to render 360 panorama
 */
function krpano_display360() {
  $resutlt = '';
  //Recover the protography id from url
  $pid = $_GET['pid'];
  if (is_numeric($pid)) {
    //Set visit
    _krpano_set_visit($pid);
    //Create xml
    $krpano = _krpano_createXML($pid);
    //Render krpano
    $resutlt = _krpano_render($krpano);
  }

  print $resutlt;
}

/*
 * Function to create the xml file to be rendered with krpano
 */
function _krpano_createXML($pid) {
  $krpano = new class_krpano($pid);
  if ($krpano->valid_data()) {
    $krpano->krpano_create_xml();
    return $krpano;
  }
  else {
    global $language;
    $message = array('en' => array('code' => '',
                                'message' => 'The panoramic view is not avalilable.'),
                     'es' => array('code' => '',
                                'message' => 'La foto 360 no esta disponible.'));
    drupal_set_message($message[$language->language]);
    drupal_goto('cloud360/error');
  }
}

/*
 * Function to display krpano
 */
function _krpano_render($krpano) {
  return $krpano->krpano_render();
}

/*
 * Function to set the visit of a photograpy
 */
function _krpano_set_visit($pid) {
  $api = 'visitPhotography';
  $postParameters = array('filter' => array('uid' => $pid,),);

  _cloud360_get_object($api, NULL, $postParameters);
}